services:
  ui:
    build: ./ui
    image: green-vault-ui
    ports: ["5173:5173"]
    env_file:
      - ./ui/.env
    depends_on:
      analyzer:
        condition: service_started
      internal:
        condition: service_started

  analyzer:
    build: ./analyzer
    image: green-vault-analyzer
    ports: ["8000:8000"]
    restart: unless-stopped
    env_file:
      - ./analyzer/.env
    depends_on:
      db:
        condition: service_healthy

  internal:
    build: ./internal
    image: green-vault-internal
    command: ["/app/server-api"]
    env_file:
      - ./internal/.env.docker
    ports: ["8080:8080"]
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  db:
    image: cgr.dev/chainguard/postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - .env.db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
